# Generated by Django 3.2.25 on 2024-05-28 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cliente_cedula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
