# Generated by Django 3.2.25 on 2024-05-28 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_producto_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenpedido',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='ordenpedido',
            name='producto',
        ),
        migrations.CreateModel(
            name='OrdenPedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('orden_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ordenpedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.producto')),
            ],
        ),
        migrations.AddField(
            model_name='ordenpedido',
            name='productos',
            field=models.ManyToManyField(through='main.OrdenPedidoProducto', to='main.Producto'),
        ),
    ]
